# Generated by Django 4.2.11 on 2024-03-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='core/static/img/alunos', verbose_name='Foto de Exibição')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('ano_ingresso', models.IntegerField(verbose_name='Ano de Ingresso')),
                ('ano_conclusao', models.IntegerField(verbose_name='Ano de Conclusão')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
            },
        ),
    ]
