# Generated by Django 4.2.11 on 2024-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/alunos', verbose_name='Foto de Exibição'),
        ),
    ]
