# Generated by Django 4.2.11 on 2024-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='core/static/img/sobre', verbose_name='Foto de Exibição')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('titulo', models.TextField(max_length=255, verbose_name='Título')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Equipe',
                'db_table': 'equipe',
            },
        ),
    ]
