# Generated by Django 4.2.11 on 2024-04-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='cadastrado_por',
            field=models.CharField(default='Julio', max_length=150, verbose_name='Cadastrado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/noticias', verbose_name='Foto de Exibição 2'),
        ),
    ]
