# Generated by Django 4.2.11 on 2024-04-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_noticia_cadastrado_por_noticia_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default='teste', max_length=150, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
    ]
