# Generated by Django 4.2.11 on 2024-03-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='core/static/img/cursos', verbose_name='Foto de Exibição')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('area_conhecimento', models.CharField(max_length=100, verbose_name='Área de Conhecimento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('titulacao', models.CharField(max_length=100, verbose_name='Titulação')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('modalidade', models.CharField(max_length=100, verbose_name='Modalidade')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
    ]
