# Generated by Django 4.2.11 on 2024-03-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NossaHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nossa História',
                'verbose_name_plural': 'Nossa História',
                'db_table': 'nossa_historia',
            },
        ),
        migrations.CreateModel(
            name='NossosValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nossos Valores',
                'verbose_name_plural': 'Nossos Valores',
                'db_table': 'nossos_valores',
            },
        ),
    ]
