# Generated by Django 4.2.11 on 2024-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/cursos', verbose_name='Foto de Exibição'),
        ),
    ]
