# Generated by Django 4.2.11 on 2024-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_nossahistoria_nossosvalores'),
    ]

    operations = [
        migrations.AddField(
            model_name='nossahistoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/nossa_historia', verbose_name='Foto de Exibição'),
        ),
        migrations.AddField(
            model_name='nossosvalores',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/nossos_valores', verbose_name='Foto de Exibição'),
        ),
    ]
